baseURL = 'https://yuukode.com'
languageCode = 'id-id'
title = 'yuukode'

enableEmoji = true
pluralizelisttitles = false

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
